[supervisord]
nodaemon=true ; Roda o supervisor no foreground, essencial para o Docker

[program:gunicorn]
# 'app:app' significa: no arquivo 'app.py', encontre o objeto 'app'
command=gunicorn --workers 2 --bind 0.0.0.0:8000 app:app
directory=/app ; Onde o comando deve ser executado
autostart=true
autorestart=true
stderr_logfile=/dev/stderr ; Envia logs de erro para o console do Docker
stdout_logfile=/dev/stdout ; Envia logs de saída para o console do Docker

[program:nginx]
command=nginx -g "daemon off;" ; Roda o Nginx no foreground
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout